### ISSUE TITLE
Grid gaps are misplaced in this example

### ISSUE THREAD

**Issue by jensimmons** [mozilla/css-grid-inspector#14]
Rachel Andrew posted in another channel: 

> Seems a bit wonky on http://gridbyexample.com/examples/code/example1.html
> (I’m using Firefox Dev edition 49.0a2)
> but this is very cool, will be highly useful to people
> looks like it is expecting a gap before the first item.

<img width="411" alt="screen shot 2016-06-15 at 12 47 02" src="https://cloud.githubusercontent.com/assets/108474/16099432/30ec28a4-3350-11e6-845b-cc9ba3f961f2.png">

**Comment by potch** [comment]
Looking pretty good now: <img width="413" alt="screenshot 2016-07-07 22 39 35" src="https://cloud.githubusercontent.com/assets/253470/16678415/b3fc5b52-4493-11e6-8a77-12411b0dfb85.png">

Going to commit this change shortly.

**Comment by potch** [comment]
Should be working now!
