### ISSUE TITLE
Always-on state

### ISSUE THREAD

**Issue by meyerweb** [mozilla/css-grid-inspector#15]
I would love if there was a way to turn this on and have it stay on as I surf from page to page.  That way, if I land on a page using grid, the grid overlay is drawn automatically.  It would be highly useful in training situations, and also for just seeing what people are doing with grid as I surf around.

**Comment by jensimmons** [comment]
Yes. We've talked about this, and I believe @potch is building it already. Thanks for the reminder. I forgot to put in on our lists, and I meant to.

**Comment by jensimmons** [comment]
Here's a question that came up when we were thinking about this.

There are different ways this could work. Different levels, almost.
Which would be more desirable?

1) When you are on a single page, and you turn on the tool, and reload the page, it loads with the tool still on. However when you surf to any other page (either your own or others), the tool is off.

2) The tool stays on upon reload for any single page, and any other page with the same root URL — so you are working on a website, and traveling from one page to another, the tool  stays open, displaying visual indications of whatever grid is on each of those pages. But if you go to another website, it's off.

3) any other variation?

My understanding from Potch is that Option 2 is much harder than Option 1 — or might be — in this Extension. And such a feature might need to wait until this is closer to the metal as a proper Firefox Dev Tool. Maybe. We were debating this. And wondering how important it would be to people for the on state to travel from one page to a different page.

Make sense? Thoughts?

**Comment by meyerweb** [comment]
I believe option 1 is much more valuable than option 2.

**Comment by potch** [comment]
I'm working on this- there's some funkiness about reloads from cache I have to figure out.

**Comment by jensimmons** [comment]
I think what we've got now works great. It doesn't stay on when going from one website to another website, but it does work fine when reloading a single page. We can revisit if this comes up again.
