### ISSUE TITLE
Grid alert!

### ISSUE THREAD

**Issue by meyerweb** [mozilla/css-grid-inspector#16]
Following on #15, it would be really great of the grid toolbar button got a little alert flag on it whenever a page with grids is loaded (unless it’s in always-on state, a la #15).  Having a little audio cue (probably optional) would be very cool, as well.

**Comment by jensimmons** [comment]
Ooo interesting. What do other people think about this?

**Comment by potch** [comment]
That is a rather slick idea! Right now, I try not to evaluate JS on the page until the user clicks the button (to avoid performance issues), but I can likely run a much-reduced snippet of code that merely *detects* the presence of grids and offer some visual feedback.

**Comment by potch** [comment]
@meyerweb I added a badge to the grid icon when grids are detected on the page- what do you think?

<img width="383" alt="screenshot 2016-06-21 10 31 24" src="https://cloud.githubusercontent.com/assets/253470/16240895/1864343a-37a0-11e6-9f30-28de6160dd45.png">

**Comment by meyerweb** [comment]
I LOVE it!

**Comment by potch** [comment]
This is landed in the latest version of the extension! https://addons.mozilla.org/en-US/firefox/addon/css-grid-inspector/
