### ISSUE TITLE
Request: ability to toggle specific grids

### ISSUE THREAD

**Issue by meyerweb** [mozilla/css-grid-inspector#8]
In pages that have multiple grids, particularly nested grids, it would be really handy to be able to toggle them on and off.  My first (possibly naïve) thought is to toggle a grid by clicking its name badge.

For example, see http://meyerweb.com/eric/css/tests/grid-figures-tdg/attaching-named-grid-lines.html.  If I could click the `#row.labels` box to flip that grid on and off, it would be super useful.  (The label would always be visible, of course; just the gridlines should be toggled.)

Following on that scheme, I’d also make shift-clicking a label a way to toggle the gridlines of every grid _except for_ the one being clicked.

**Comment by jensimmons** [comment]
+1

One complication is that it's not uncommon for multiple Grids to have the same starting place. Which, at the moment, means the labels stack on top of each other. 

For example: http://labs.jensimmons.com/examples/grid-content-1.html

If the labels become actionable buttons, then this overlap problem becomes a bigger deal. Perhaps we can make it so a second label slides over to not be under the first one...

**Comment by jensimmons** [comment]
Update: this is in progress. Cross your fingers!

**Comment by potch** [comment]
This is totes working:
<img width="325" alt="screenshot 2016-07-07 23 07 26" src="https://cloud.githubusercontent.com/assets/253470/16694888/90d039b0-44f1-11e6-8e8c-f598f370a1c5.png">
